namespace Mollie.Api.Models.Connect {
    public class AuthorizeRequest {
        /// <summary>
        ///     The client ID you receive when registering your app.
        /// </summary>
        public string ClientId { get; set; }

        /// <summary>
        ///     Optional – The URL the merchant is sent back to once the request has been authorized. If given, it must match the
        ///     URL you set when registering your app.
        /// </summary>
        public string RedirectUri { get; set; }

        /// <summary>
        ///     A random string generated by your app to prevent CSRF attacks.
        /// </summary>
        public string State { get; set; }

        /// <summary>
        ///     A space separated list of permissions your app requires. Refer to OAuth: Permissions for more information about the
        ///     available scopes.
        /// </summary>
        public string Scope { get; set; }

        /// <summary>
        ///     Mollie currently only replies with code responses.
        ///     Possible values: code
        /// </summary>
        public string ResponseType { get; set; }

        /// <summary>
        ///     This parameter can be set to force, to force showing the consent screen to the merchant, even when it is not
        ///     necessary.
        ///     Possible values: auto force
        /// </summary>
        public string ApprovalPrompt { get; set; }
    }
}